### ISSUE TITLE
The ESC globalShortcut is sometimes misleading

### ISSUE THREAD

**Issue by ademcan** [FlorianFe/EasyTongue#2]
Hi, 
Thanks for this tool, it is very convenient and works well.
However, it seems that there is a globalShortcut for the ESC key and this can sometimes be misleading. At the beginning I thought my ESC key was broken, then I found out that it was working for EasyTongue. You could maybe register the globalShortcut only when the EasyTongue window is open and after the first ESC pressed (and the window closed) unregister it (?).
My 2 cents...

**Comment by FlorianFe** [comment]
Did you use version 1.0.2 or below?

**Comment by ademcan** [comment]
Yes, it seems that I am using 1.0.0 and you are already at 1.0.4. I didn't see all the updates :) I will check the latest version. Thanks.

**Comment by FlorianFe** [comment]
No problem 😁 Unfortunately the API this app was using is not longer supported. So the app won't work till i found a new one.
